[versions]
coroutines = "1.8.1"
mockative = "2.2.1"
mockk = "1.13.11"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.0" }
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.8.0" }
androidx-startup = { module = "androidx.startup:startup-runtime", version = "1.1.1" }
turbine = { module = "app.cash.turbine:turbine", version = "1.1.0" }
robolectric = { module = "org.robolectric:robolectric", version = "4.12.2" }
mockative = { module = "io.mockative:mockative", version.ref = "mockative" }
mockative-processor = { module = "io.mockative:mockative-processor", version.ref = "mockative" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-agent-jvm = { module = "io.mockk:mockk-agent-jvm", version.ref = "mockk" }
